### PR TITLE
build: fully remove requests dep

### PR DESCRIPTION
**Pull request by fanquake**
Otherwise this fails to build.

### CODE REVIEW

**Comment by achow101** [comment]
ACK 5aad5b278224a42a2574a3ca93e020e80182151a

**Comment by fanquake** [comment]
> and play around with removing the setup.py.

Just note that if that is removed, we'll likely need to change our package definition in our Guix manifest, to use a different install method. However, that can be dealt with at the bump after next.

**Comment by achow101** [comment]
> we'll likely need to change our package definition in our Guix manifest, to use a different install method

From https://guix.gnu.org/manual/en/html_node/Python-Modules.html

>  pyproject-build-system is Guix’s implementation of this standard. It is considered “experimental” in that it does not yet support all the various PEP-517 build backends, but you are encouraged to try it for new Python packages and report any problems. It will eventually be deprecated and merged into python-build-system. 

It'll probably be ready for the next release?

**Comment by fanquake** [comment]
Yea, I don't think it'll be an issue.

**Pull request merged**
